// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClipboardInfo = { has_files: boolean, paths: Array<string>, is_cut: boolean, file_count: number, file_summary: string | null, has_image: boolean, image_data: string | null, };