// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskInfo } from "./DiskInfo";

export type FileEntry = { name: string, path: string, is_dir: boolean, size: number, formatted_size: string, file_type: string, created_at: string, modified_at: string, is_shortcut: boolean, disk_info: DiskInfo | null, modified_timestamp: number, dimensions: string | null, };