// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecycleBinStatus = { is_empty: boolean, item_count: number, total_size: number, };