// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderSizeUpdate = { path: string, req_id: string, size: number, formatted_size: string, };