name: Publish to WinGet
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: WinGet Releaser
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          # Token de seguridad guardado en tus Secrets
          token: ${{ secrets.WINGET_TOKEN }}
          
          # ID oficial de tu paquete
          identifier: biondi53.QuickExplorer
          
          # Filtro para detectar solo los archivos .msi
          installers-regex: '\.msi$'
